2024/02/06 15:16:24 PyTic        INFO     Network is connected - Keysight Technologies,N5234B,MY58421805,A.14.80.08
2024/02/06 15:16:24 PyTic        INFO     Network configed
2024/02/06 15:16:24 PyTic        INFO     Newmark is connected at COM5
2024/02/06 15:16:24 PyTic        INFO     Positioner is connected
2024/02/06 15:16:24 __main__     INFO     Positioner: None, Gimbal: None, Signal: None
2024/02/06 15:16:27 PyTic        INFO     System mode set to - idle
2024/02/06 15:16:27 PyTic        INFO     System mode set to - track_signal
2024/02/06 15:16:27 PyTic        INFO     Gimbal speed set to: (10, 10) [deg/sec]
2024/02/06 15:16:27 PyTic        INFO     Gimbal acceleration set to: (5, 5) [deg/sec^2]
2024/02/06 15:16:27 PyTic        INFO     Algo=DiscreteTrackingAlgo, init_step_size=0.3, init_jitter_step=0.3
2024/02/06 15:16:27 PyTic        INFO     time_between_nodes=0.4
2024/02/06 15:16:29 __main__     INFO     Positioner: (1.5, 0.0), Gimbal: (-0.1, -0.2), Signal: -55.5
2024/02/06 15:16:34 __main__     INFO     Positioner: (1.5, 0.0), Gimbal: (-0.3, -0.4), Signal: -53.6
2024/02/06 15:16:39 __main__     INFO     Positioner: (1.5, 0.0), Gimbal: (-0.6, -0.6), Signal: -49.4
2024/02/06 15:16:44 __main__     INFO     Positioner: (1.5, 0.0), Gimbal: (-1.2, -0.3), Signal: -45.6
2024/02/06 15:16:49 __main__     INFO     Positioner: (1.5, 0.0), Gimbal: (-1.6, 0.1), Signal: -43.9
2024/02/06 15:16:52 __main__     INFO     Positioner: (1.5, 0.0), Gimbal: (-1.6, 0.1), Signal: -42.9
2024/02/06 15:16:55 __main__     INFO     Positioner: (1.5, 0.0), Gimbal: (-1.6, 0.1), Signal: -44.9
2024/02/06 15:17:00 __main__     INFO     Positioner: (1.5, 0.0), Gimbal: (-1.6, 0.1), Signal: -44.1
2024/02/06 15:17:05 __main__     INFO     Positioner: (1.5, 0.0), Gimbal: (-1.6, 0.1), Signal: -44.3
2024/02/06 15:17:10 __main__     INFO     Positioner: (1.5, 0.0), Gimbal: (-1.6, 0.1), Signal: -43.8
2024/02/06 15:16:54 __main__     INFO     User cmd: exit
2024/02/06 15:16:54 asyncio      ERROR    Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Positioner.update_position() done, defined at C:\Users\robert\OneDrive - nslcomm.com\Python\GDA_demo\devices.py:143> exception=SyntaxError('unexpected EOF while parsing', ('<string>', 0, 0, ''))>
Traceback (most recent call last):
  File "C:\Users\robert\OneDrive - nslcomm.com\Python\GDA_demo\devices.py", line 146, in update_position
    await self.get_position()
  File "C:\Users\robert\OneDrive - nslcomm.com\Python\GDA_demo\devices.py", line 136, in get_position
    rec = eval(rec.decode())
  File "<string>", line 0
    
SyntaxError: unexpected EOF while parsing
2024/02/06 15:16:54 PyTic        INFO     Positioner disconnected
2024/02/06 15:16:54 PyTic        INFO     Newmark disconnected
2024/02/06 15:16:54 PyTic        INFO     Network is disconnected
